version: '3.8'

services:
  app:
    container_name: app-especiais
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-shared:5432/api-transferegov
      - REDIS_URL=redis://redis-shared:6379/1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-especiais.rule=Host(`api.kingdomsys.com`)&&PathPrefix(`/api-especiais`)"
      - "traefik.http.routers.api-especiais.entrypoints=websecure"
      - "traefik.http.routers.api-especiais.tls=true"
      - "traefik.http.routers.api-especiais.tls.certresolver=letsencrypt"
      - "traefik.http.services.api-especiais.loadbalancer.server.port=8000"
       # Adicione esta configuração para WebSockets
      - "traefik.http.routers.api-especiais-ws.rule=Host(`api.kingdomsys.com`) && PathPrefix(`/api-especiais/ws`)"
      - "traefik.http.routers.api-especiais-ws.entrypoints=websecure"
      - "traefik.http.routers.api-especiais-ws.tls=true"
      - "traefik.http.routers.api-especiais-ws.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api-especiais-ws.service=api-especiais"

networks:
  default:
    name: web-apps
    external: true
