version: '3.8'

services:
  app:
    container_name: app-especiais
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-shared:5432/api-transferegov
      - REDIS_URL=redis://cache-especiais:6379/0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-especiais.rule=PathPrefix(`/api-especiais`)"
      - "traefik.http.routers.api-especiais.entrypoints=web"
      - "traefik.http.services.api-especiais.loadbalancer.server.port=8000"
       # Adicione esta configuração para WebSockets
      - "traefik.http.middlewares.api-especiais-ws.headers.customRequestHeaders.X-Forwarded-Proto=ws"
      - "traefik.http.routers.api-especiais-ws.rule=PathPrefix(`/api-especiais/ws`)"
      - "traefik.http.routers.api-especiais-ws.entrypoints=web"
      - "traefik.http.routers.api-especiais-ws.service=api-especiais"
      - "traefik.http.routers.api-especiais-ws.middlewares=api-especiais-ws"

  redis:
    container_name: cache-especiais
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  default:
    name: web-apps
    external: true
